import { TestBed } from '@angular/core/testing';
import { Api, ApiFailure } from './api';
import { Organization } from './organization';
describe('Organization',()=>{
  let request:ReturnType<typeof vi.fn>;
  const task={id:'5',taskDate:'2026-12-31',title:'Shared task',description:'Description',status:'PENDING',version:'v1',authorName:'Author',updatedByName:'Editor',updatedAt:'2026-12-31T12:00:00Z'};
  beforeEach(()=>{request=vi.fn().mockImplementation((path:string)=>Promise.resolve(path.startsWith('/calendar')?{month:path.includes('month=')?path.split('month=')[1]:'2026-12',serverDate:'2026-12-31',days:[{date:'2026-12-31',reservations:2,tasks:1,pendingTasks:1}]}:{items:path.startsWith('/tasks')?[task]:[],page:0,size:20,total:path.startsWith('/tasks')?1:0}));TestBed.configureTestingModule({providers:[{provide:Api,useValue:{request,reset:vi.fn()}}]});});
  afterEach(()=>vi.restoreAllMocks());
  async function component(){const fixture=TestBed.createComponent(Organization);fixture.componentRef.setInput('user',{id:'1',role:'STAFF',name:'Staff',username:'staff'});await fixture.whenStable();return fixture;}
  it('navigates across years and returns to the server date',async()=>{const fixture=await component();const c=fixture.componentInstance;expect(c.selected).toBe('2026-12-31');expect(fixture.nativeElement.textContent).toContain('Shared task');await c.shift(1);expect(c.calendar()?.month).toBe('2027-01');expect(c.selected).toBe('2027-01-01');await c.today();expect(c.selected).toBe('2026-12-31');});
  it('preserves an edited task after a conflict and confirms deletion',async()=>{const fixture=await component();const c=fixture.componentInstance;c.edit(task);c.draft.title='My edit';c.dirty=true;request.mockRejectedValue(new ApiFailure('VERSION_CONFLICT',{},409));await c.save();expect(c.draft.title).toBe('My edit');expect(c.editing()).toBe(true);expect(c.error()).toBe('VERSION_CONFLICT');vi.spyOn(window,'confirm').mockReturnValue(false);c.cancel();expect(c.editing()).toBe(true);request.mockClear();c.dirty=false;await c.remove(task);expect(request).not.toHaveBeenCalled();});
  it('retries an uncertain creation with the same key and body',async()=>{const fixture=await component();const c=fixture.componentInstance;c.edit();c.draft.title='New task';c.draft.description='Task detail';const original=request.getMockImplementation()! as (...args:unknown[])=>unknown;let attempt=0;request.mockImplementation((path:string,method?:string,...rest:unknown[])=>method==='POST'?(++attempt===1?Promise.reject(new ApiFailure('NETWORK_ERROR',{},0)):Promise.resolve(task)):original(path,method,...rest));await c.save();expect(c.uncertain()).toBe(true);expect(c.canLeave()).toBe(false);await c.recover();const writes=request.mock.calls.filter(call=>call[1]==='POST');expect(writes).toHaveLength(2);expect(writes[0]).toEqual(writes[1]);expect(c.uncertain()).toBe(false);});
});
